// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDANWunbruByDZwpy-oqh8mcXBBZ0ZBQj4',
    appId: '1:9663580275:web:2d88ec0726caa54952c206',
    messagingSenderId: '9663580275',
    projectId: 'chatapp-6a5a1',
    authDomain: 'chatapp-6a5a1.firebaseapp.com',
    storageBucket: 'chatapp-6a5a1.firebasestorage.app',
    measurementId: 'G-SBM30F3WSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs3Ch2keDmJ24e3-vvTcJge481ukp3MKw',
    appId: '1:9663580275:android:119a33c3921d61f952c206',
    messagingSenderId: '9663580275',
    projectId: 'chatapp-6a5a1',
    storageBucket: 'chatapp-6a5a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4q5C1zEh4VwCr_ow0k6B0EgUzfqGCL2I',
    appId: '1:9663580275:ios:31d9376ce9fdfc5252c206',
    messagingSenderId: '9663580275',
    projectId: 'chatapp-6a5a1',
    storageBucket: 'chatapp-6a5a1.firebasestorage.app',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );
}
